# Generated by Django 4.2.15 on 2024-09-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
